name: ConQueDoctor
description: "Una ayuda para tu gestion de Salud."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  provider: ^6.0.3
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6
  url_launcher: ^6.1.10
  # Firebase dependencies
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  http: ^0.13.3
  geolocator: ^9.0.2
  diacritic: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/procedimientos_medicos.json
    - assets/data/especialidades.json
    - assets/avatar.png
    - assets/ficha_medica.png
    - assets/centros_medicos.png
    - assets/especialidades.png
    - assets/profesionales.png
    - assets/coberturas.png
    - assets/cardiologia.png
    - assets/kinesiologia.png
    - assets/medicina_general.png
    - assets/radiologia.png
    - assets/dental.png
    - assets/maternidad.png
    - assets/doctor1.png
    - assets/doctor2.png
    - assets/doctor3.png
